### ISSUE TITLE
BSCD contains the locations of 46050 BSes run by CMCC and CUCC in Chendu City collected in Dec. 2019, among which 1910 BSes in the northeast of the city (30.653°N - 30.705°N and 104.042°E - 104.122°E) are utilized in the performance evaluation. 2) DECD18 includes the trajectories of Didi expresses in Chendu City during Oct 8, 2018 - Oct 31, 2018. The location of each express is updated every 20 seconds.  数据集 BSCD DECD18 能提供一下吗

### ISSUE THREAD

**Issue by Phil610351** [Tnnidm/golang-leetcode#1]
BSCD
contains the locations of 46050 BSes run by CMCC and
CUCC in Chendu City collected in Dec. 2019, among which
1910 BSes in the northeast of the city (30.653°N - 30.705°N
and 104.042°E - 104.122°E) are utilized in the performance
evaluation. 2) DECD18 includes the trajectories of Didi
expresses in Chendu City during Oct 8, 2018 - Oct 31, 2018.
The location of each express is updated every 20 seconds.

数据集 BSCD DECD18 能提供一下吗

**Comment by Tnnidm** [comment]
你好，你Issue提错地方了，这不是好的沟通方式。

**Comment by Phil610351** [comment]
不好意思，大佬能发一份数据集吗，2647790445@qq.com

**Comment by Phil610351** [comment]
***@***.***
不好意思，大佬，如果方便的话能否发一份数据给我。



---原始邮件---
发件人: "Suhong ***@***.***&gt;
发送时间: 2022年3月18日(周五) 上午10:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Tnnidm/golang-leetcode] BSCD contains the locations of 46050 BSes run by CMCC and CUCC in Chendu City collected in Dec. 2019, among which 1910 BSes in the northeast of the city (30.653°N - 30.705°N and 104.042°E - 104.122°E) are utilized in the performance evaluation. 2) DECD18 includes the trajectories of Didi expresses in Chendu City during Oct 8, 2018 - Oct 31, 2018. The location of each express is updated every 20 seconds.  数据集 BSCD DECD18 能提供一下吗 (Issue #1)




 
你好，你Issue提错地方了，这不是好的沟通方式。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
