### ISSUE TITLE
'chengdushi_1010_1020.csv', 这个文件的数据格式能说一下吗，大佬，您的数据处理的看不懂。或者给个chengdushi_1010_1020.csv文件

### ISSUE THREAD

**Issue by Phil610351** [Tnnidm/golang-leetcode#2]
'chengdushi_1010_1020.csv', 这个文件的数据格式能说一下吗，大佬，您的数据处理的看不懂。或者给个chengdushi_1010_1020.csv文件

**Comment by Phil610351** [comment]
'chengdushi_1010_1020.csv', 这个文件的数据格式能说一下吗，大佬，您的数据处理的看不懂。或者给个chengdushi_1010_1020.csv文件

**Comment by Tnnidm** [comment]
抱歉，作为一个学生，我没权限开放当时以实验室名义申请的数据集，而且滴滴的条款也要求不能传播这个数据集。实际上你用任何一个城市的车辆轨迹数据集讲道理都可以复现结果，并不一定要纠结于成都的数据集。'chengdushi_1010_1020.csv'文件有很多列，但是实际上用到的只有时间戳和位置信息，其他的我有点忘了，因为是本科时候写的代码了
